### ISSUE TITLE
Requests return 404 error

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/twitter-extraction#1]
I'm testing twitter-extraction and I cannot get a response (HTTP 200 response). Always it returns me a 404 error.

I followed the instructions (https://github.com/OpenReqEU/twitter-extraction) but  launching the application in python as well as with docker, it doesn't work.

I test it in command line and web browser and it always returns "404 not found"
I test it : 
localhost:9005
localhost:9005/ui
localhost:9005/swagger.json  
localhost:9005/popularity/hashtag 

Log:
* Running on http://0.0.0.0:9005/ (Press CTRL+C to quit)
ip - - [11/Mar/2019 14:49:41] "GET /swagger.json HTTP/1.1" 404 -
ip - - [11/Mar/2019 14:49:42] "GET /swagger.json HTTP/1.1" 404 -

With curl command:
{
  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}

Am I doing something wrong? Can you help me?

**Comment by vvalvesga** [comment]
More info:
Operating System: Ubuntu 18.04.2 LTS
Kernel: Linux 4.15.0-46-generic
Architecture: x86-64

**Comment by jnerlich** [comment]
@dfucci @mstettinger Any update here?

**Comment by rsamer** [comment]
Sorry, there was something wrong with the path in the Readme description.
Please consider the prefix "v1/" as base path in the URLs.

localhost:9005/v1/ui
localhost:9005/v1/swagger.json
localhost:9005/v1/popularity/hashtag

**Comment by vvalvesga** [comment]
ok, it works!

Thanks
