### ISSUE TITLE
trainWord2vec not works

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/twitter-extraction#2]
When I call this service I get a 500 Error response.

Request POST body:  
```
"tweets":[{"message":"Posso essere chiamato da un operatore 3"},
    {"message":"Ci sono appena andato a un negozio e o faccio una promozione o niente! Voglio pagare quando chiamo e non vo "}]}
```

Response: 500
Logs:

> 2019-04-03 09:16:06,719 : INFO : 155.210.136.192 - - [03/Apr/2019 09:16:06] "OPTIONS /analytics-backend/cleanText HTTP/1.1" 200 -
> 2019-04-03 09:16:06,729 - __main__ - INFO - /analytics-backend/cleanText
> 2019-04-03 09:16:06,729 : INFO : /analytics-backend/cleanText
> 2019-04-03 09:16:06,779 : INFO : 155.210.136.192 - - [03/Apr/2019 09:16:06] "POST /analytics-backend/cleanText HTTP/1.1" 200 -
> 2019-04-03 09:16:23,212 : INFO : 155.210.136.192 - - [03/Apr/2019 09:16:23] "OPTIONS /analytics-backend/trainWord2Vec HTTP/1.1" 200 -
> 2019-04-03 09:16:23,222 - __main__ - INFO - /analytics-backend/trainWord2Vec
> 2019-04-03 09:16:23,222 : INFO : /analytics-backend/trainWord2Vec
> 2019-04-03 09:16:23,261 - core.corpus - INFO - GET ENTITIES
> 2019-04-03 09:16:23,261 : INFO : GET ENTITIES
> 2019-04-03 09:18:33,056 : ERROR : Exception on /analytics-backend/trainWord2Vec [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "app.py", line 1113, in trainWord2Vec
>     corpus = Corpus.createCorpus(cleaned_input_list)
>   File "/app/core/corpus.py", line 21, in createCorpus
>     entity_list, tweet_with_entity_list, all_uri = getEntities(cleaned_input_list, confidence=confidence)
>   File "/app/core/corpus.py", line 38, in getEntities
>     out_uri_list, out_entities_list, out_text_list = applyAnnotateSenteceOnList(cleaned_list, confidence=confidence)
>   File "/app/core/corpus.py", line 110, in applyAnnotateSenteceOnList
>     out_uri, out_entities, out_text, sentence = core.Annotation_Library.annotateSentence(text, language=language, confidence=confidence)
>   File "/app/core/Annotation_Library.py", line 30, in annotateSentence
>     req = requests.post(os.path.join(baseAdress, 'keywords/supervised'), json.dumps(my_data), None)
>   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 116, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> ConnectionError: HTTPConnectionPool(host='193.109.207.65', port=15024): Max retries exceeded with url: /nlp/keywords/supervised (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e4962d8d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> 2019-04-03 09:18:33,061 : INFO : 155.210.136.192 - - [03/Apr/2019 09:18:33] "POST /analytics-backend/trainWord2Vec HTTP/1.1" 500 -
>

**Comment by vvalvesga** [comment]
Close because I got confused, sorry

**Comment by rsamer** [comment]
Please bear in mind that we don’t use word2vec in this service.
