### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/twitter-extraction#3]
Hi,

When I call this service I get a 500 internal server error.

Request:

http://localhost:9005/v1/popularity
Body:
```
[
  {
    "description": "string",
    "id": 0,
    "title": "string"
  }
]
```

Log:

> [2019-04-03 10:52:19,174] ERROR in app: Exception on /v1/popularity [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
>     response = function(request)
>   File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 122, in wrapper
>     response = function(request)
>   File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 293, in wrapper
>     return function(request)
>   File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
>     response = function(request)
>   File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 218, in wrapper
>     return function(**kwargs)
>   File "/usr/src/app/application/controllers/hashtag_controller.py", line 65, in compute_popularity
>     enable_stemming=False)
>   File "/usr/src/app/application/preprocessing/preprocessing.py", line 171, in preprocess_requirements
>     pos.pos_tagging(requirements)
>   File "/usr/src/app/application/preprocessing/pos.py", line 141, in pos_tagging
>     pos_tagged_requirement_tokens = pos_tagger.tag(corrected_words)
>   File "/usr/local/lib/python3.7/site-packages/nltk/tag/stanford.py", line 81, in tag
>     return sum(self.tag_sents([tokens]), [])
>   File "/usr/local/lib/python3.7/site-packages/nltk/tag/stanford.py", line 86, in tag_sents
>     config_java(options=self.java_options, verbose=False)
>   File "/usr/local/lib/python3.7/site-packages/nltk/internals.py", line 58, in config_java
>     _java_bin = find_binary('java', bin, env_vars=['JAVAHOME', 'JAVA_HOME'], verbose=verbose, binary_names=['java.exe'])
>   File "/usr/local/lib/python3.7/site-packages/nltk/internals.py", line 604, in find_binary
>     binary_names, url, verbose))
>   File "/usr/local/lib/python3.7/site-packages/nltk/internals.py", line 598, in find_binary_iter
>     url, verbose):
>   File "/usr/local/lib/python3.7/site-packages/nltk/internals.py", line 569, in find_file_iter
>     raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
> LookupError:
> 
> >=============================================================>==============
> NLTK was unable to find the java file!
> Use software specific configuration paramaters or set the JAVAHOME environment variable.
> >=============================================================>==============
> 155.210.136.192 - - [03/Apr/2019 10:52:19] "POST /v1/popularity HTTP/1.1" 500 -

**Comment by rsamer** [comment]
Dear Volodymyr (?),

Providing the template as body of the request is not very meaningful and does not make much sense.
Instead use some meaningful information such as:

```
[
  {
    "id": 1,
    "title": "Distance Measurement",
    "description": "For statistical purposes, a distance measurement is necessary which needs data from a GPS sensor. This data is needed for the evaluation software and therefore stored in memory."
  },
  {
    "id": 2,
    "title": "Speed Measurement",
    "description": "As evaluation after a workout, the average speed must be shown. The following statistics should be displayed: average speed and maximum speed. For measuring the average and maximum speed, time and distance have to be measured, and a storage unit for storing the data is necessary."
  }
]
```

**Comment by vvalvesga** [comment]
Hi Ralph,

My name is Victor :)

You're right but what I wanted to show was the error that gives me back this call.

I tried with that body and it also gives me the same error

**Comment by dfucci** [comment]
@rsamer any updates on this?

**Comment by mstettinger** [comment]
Hi Victor,

we checked the service and your log again ...

The error occurs because on your machine the JAVA_HOME variable cannot be found -- see the bottom of your error log which says "NLTK was unable to find the java file! Use software specific configuration parameters or set the JAVAHOME environment variable." 

we use POS tagging to recognize nouns which are then used to analyze the tweets ... For this we call the Python NLTK library but this library calls the standard POS tagger which is developed in Java which is the reason why (1) Java has to be installed on your system as well as (2) the JAVA_HOME variable has to be set correctly.

Due to the fact that your log searches for java.exe we believe you are running the service on a Windows machine ... If so, the following post should help you in installing Java and setting the JAVA_HOME variable: https://stackoverflow.com/questions/2619584/how-to-set-java-home-on-windows-7 

Hope that helps you.

Best,

**Comment by jnerlich** [comment]
@vvalvesga Does this solve your issue?

**Comment by vvalvesga** [comment]
Hello

The problem occurred in Docker.

I put this in the docker file and I managed not to display the message "NLTK could not find the java file! Use specific software configuration parameters or configure the JAVAHOME environment variable".

```
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:openjdk-r/ppa
RUN apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
```

But now, when I launch the same request I get this in the log:
```
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:9005/ (Press CTRL+C to quit)
POS Tagging enabled!
ERROR:flask.app:Exception on /v1/popularity [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 122, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 293, in wrapper
    return function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 218, in wrapper
    return function(**kwargs)
  File "/usr/src/app/application/controllers/hashtag_controller.py", line 79, in compute_popularity
    maut_temp += fetch_twitter(token)
  File "/usr/src/app/application/controllers/hashtag_controller.py", line 31, in fetch_twitter
    for item in response:
  File "/usr/local/lib/python3.6/site-packages/TwitterAPI/TwitterAPI.py", line 206, in __iter__
    return self.get_iterator()
  File "/usr/local/lib/python3.6/site-packages/TwitterAPI/TwitterAPI.py", line 193, in get_iterator
    raise TwitterRequestError(self.response.status_code)
TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (403)
155.210.136.192 - - [24/Apr/2019 08:58:55] "POST /v1/popularity HTTP/1.1" 500 -
INFO:werkzeug:155.210.136.192 - - [24/Apr/2019 08:58:55] "POST /v1/popularity HTTP/1.1" 500 -
```

It still does not work

**Comment by rsamer** [comment]
Hello Victor,

thank you for your feedback.
It seems that you successfully got rid of this error message but faced another issue.
The error returned by the application is of type 403 - which means forbidden.
The reason for this is that the authentication credentials are not set correctly.

Please register for a developer account on http://developer.twitter.com first.
After that (please) go to application/twitter/twitter.py and fill in the following fields:
```
consumer_key = 'YOUR_CONSUMER_KEY'
consumer_secret = 'YOUR_CONSUMER_SECRET'
access_token = 'YOUR_ACCESS_TOKEN'
access_secret = 'YOUR_SECRET_TOKEN'
```

Best regards,
Ralph

**Comment by dfucci** [comment]
@vvalvesga @rsamer thanks for your efforts. 
The original issue seems to have been addressed.
